/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ActivityStatusOverlay: typeof import('./src/components/ActivityStatusOverlay.vue')['default']
    CheckinMeter: typeof import('./src/components/CheckinMeter.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElStatistic: typeof import('element-plus/es')['ElStatistic']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    FlowChart: typeof import('./src/components/FlowChart.vue')['default']
    LoadingAnimation: typeof import('./src/components/LoadingAnimation.vue')['default']
    SciFiTypewriterTable: typeof import('./src/components/SciFiTypewriterTable.vue')['default']
    SheetSelector: typeof import('./src/components/SheetSelector.vue')['default']
    StudentDashboard: typeof import('./src/components/StudentDashboard.vue')['default']
    StudentTable: typeof import('./src/components/StudentTable.vue')['default']
    TypeStatistics: typeof import('./src/components/TypeStatistics.vue')['default']
    UnifiedOverlay: typeof import('./src/components/UnifiedOverlay.vue')['default']
  }
}
